image: Visual Studio 2022

version: 1.0.{build}

branches:
  only:
  - master

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\CommonTK.Console
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

artifacts:
  - path: CommonTK.Console\bin\Release\SAPTeam.CommonTK.Console.*nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: 2JgiRhKTzQyXmzR9JYLL6f9aNfxEKvr0pF0NxqQ1YY59O1Z5xQqI9kmDgFEiJe4y
  skip_symbols: false
