image: Visual Studio 2022

version: 1.0.{build}

branches:
  only:
  - master

install:
  - git submodule init
  - git submodule update


build_script:
  - cmd: dotnet pack CommonTK.Console\CommonTK.Console.csproj -c Release
  - cmd: dotnet pack CommonTK.Console.Client\CommonTK.Console.Client.csproj -c Release

artifacts:
  - path: CommonTK.*\bin\Release\SAPTeam.CommonTK.*.*nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: 2JgiRhKTzQyXmzR9JYLL6f9aNfxEKvr0pF0NxqQ1YY59O1Z5xQqI9kmDgFEiJe4y
  skip_symbols: false
